SE-465: Fix mixed lookthrough instrument upload
finbourne/lusid-python-tools pull request #166
Opened 2020-11-13 13:06 UTC by thomasdotred

SE-465: Initial fix

SE-465: Add tests for lookthrough instruments upsert
Allow non lookthrough and lookthrough instruments to be upserted in the same dataframe.

# Pull Request Checklist

- [ ] Read the [contributing guidelines](https://github.com/finbourne/lusid-python-tools/blob/master/docs/CONTRIBUTING.md)
- [ ] Tests pass

# Description of the PR

Allows load from data frame to upsert a mixture of conventional and lookthrough instruments

2020-11-13 14:25 UTC, rizwansaeed requested changes

2020-11-13 14:25 UTC, rizwansaeed commented on lusidtools/cocoon/utilities.py
> +    missing_value = False
do we need some tests specifically around these changes too?

2020-11-13 18:16 UTC, thomasdotred commented on tests/integration/cocoon/test_cocoon_instruments.py
> +    def test_load_instrument_lookthrough(self, _, df, mapping):
same instrument id will be covered by instrument upsert tests that throw errors if multiple instruments of the same type are included in the same dataframe
![image](https://user-images.githubusercontent.com/47391762/99106537-496f5d00-25dc-11eb-9092-68188705d7fe.png)

2020-11-30 10:35 UTC, thomasdotred commented on tests/integration/cocoon/test_cocoon_instruments.py
> +        code = create_scope_id()
added teardown for this test. 
Maybe in the future we should move towards tagging all scopes with some prefix, then have a generic teardown that runs after all unit tests and deletes every related portfolio, property definition, quote, recipe etc?

2020-11-30 12:21 UTC, thomasdotred commented on tests/integration/cocoon/test_cocoon_instruments.py
> +    def test_load_instrument_lookthrough(self, _, df, mapping):
Including different instruments same portfolio in next push

2020-12-04 13:23 UTC, closed without merging